[package]
name = "tomlplusplus"
version = "3.4.0"
desc = "C++ library for using TOML code in projects"

[dependencies]

[system]
owner = ""
custom-root = ""
triggers = []
license = ""

[security]
requires = "none"
deprecated = false
permission = "none"
