[package]
name = "hello_world"
version = "1.0.2"
desc = "A dummy package for testing if bupm works."

[dependencies]
direct = []
pulled = []

[system]
owner = ""
custom-root = ""
triggers = []
license = ""

[security]
requires = "none"
deprecated = false
permission = "none"
