[package]
name = "hello_deps"
version = "1.0.0"
desc = "bupm test package - dependency handling"

[dependencies]
direct = ["hello-world"]

[system]
owner = ""
custom-root = ""
triggers = []
license = ""

[security]
requires = "none"
deprecated = false
permission = "none"
